{{- range $configMapName, $configMap := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "velero.fullname" $ }}-{{ $configMapName }}
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "velero.labels" . | indent 4 }}
  {{- with $configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
---
{{- end }}
