{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "velero.fullname" . }}-server
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "velero.labels" . | indent 4 }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"

{{- end }}
