{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "velero.fullname" . }}
  {{- if or .Values.customAnnotations .Values.metrics.service.annotations }}
  annotations:
    {{- if .Values.metrics.service.annotations }}
    {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
    {{- end }}
    {{- with .Values.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "velero.labels" . | indent 4 }}
    {{- with .Values.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-monitoring
      port: 8085
      targetPort: http-monitoring
  selector:
    {{- include "velero.selectorLabels" . | indent 4 }}
{{- end }}
