{{- if .Values.serviceAccount.crds.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero.crdsServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- if .Values.serviceAccount.crds.annotations }}
{{ toYaml .Values.serviceAccount.crds.annotations | nindent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
{{- end }}
